ovn-rundir: /var/run/ovn
ovs-rundir: /var/run/openvswitch
collectors: ['ovn', 'vswitch', 'bridge', 'coverage', 'datapath', 'iface', 'memory']
{{- if .TLS }}
web-config: /etc/config/web-config.yaml
{{- end }}
